[package]
name = "path_search_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
pancurses = "0.17"
rand = "0.8.4"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "perfomance"
harness = false

[lib]
bench = false